# Generated by Django 6.0.5 on 2026-06-01 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('symbol', models.CharField(blank=True, max_length=32)),
                ('isin', models.CharField(blank=True, max_length=32)),
                ('product_type', models.CharField(choices=[('token', 'Token'), ('stock', 'Stock'), ('bond', 'Bond'), ('crypto', 'Crypto'), ('cfd', 'CFD'), ('deposit', 'Deposit'), ('etf', 'ETF'), ('other', 'Other')], default='other', max_length=32)),
                ('units', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('current_price', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('current_value_usd', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('external_id', models.CharField(blank=True, max_length=128)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='common.currency')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='institutions.financialinstitution')),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('institution', 'external_id'), name='unique_product_external_id_per_institution')],
            },
        ),
    ]
