# Generated by Django 6.0.5 on 2026-06-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='annual_rate_pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='term_months',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='maturity_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='income_schedule',
            field=models.CharField(
                blank=True,
                choices=[
                    ('monthly', 'Monthly'),
                    ('quarterly', 'Quarterly'),
                    ('semi_annual', 'Semi-annual'),
                    ('annual', 'Annual'),
                    ('at_maturity', 'At maturity'),
                    ('other', 'Other'),
                ],
                default='',
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name='product',
            name='next_income_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='terms_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
