# Generated by Django 6.0.5 on 2026-06-04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_token_terms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='term_months',
        ),
    ]
