# Generated by Django 6.0.5 on 2026-06-05

from django.db import migrations, models


class Migration(migrations.Migration):

	dependencies = [
		('products', '0004_product_income_account'),
	]

	operations = [
		migrations.AlterField(
			model_name='product',
			name='product_type',
			field=models.CharField(
				choices=[
					('token', 'Token'),
					('stock', 'Stock'),
					('bond', 'Bond'),
					('crypto', 'Crypto'),
					('cfd', 'CFD'),
					('deposit', 'Deposit'),
					('etf', 'ETF'),
					('pension', 'Pension'),
					('other', 'Other'),
				],
				default='other',
				max_length=32,
			),
		),
	]
