# Generated by Cursor on 2026-06-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='units',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
    ]
