# Generated by Django 6.0.5 on 2026-06-01 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialInstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('institution_type', models.CharField(choices=[('bank', 'Bank'), ('broker', 'Broker'), ('crypto_exchange', 'Crypto exchange'), ('insurance', 'Insurance'), ('other', 'Other')], default='bank', max_length=32)),
                ('country', models.CharField(default='BY', max_length=2)),
                ('website', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('base_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='institutions', to='common.currency')),
            ],
            options={
                'verbose_name': 'Financial institution',
                'verbose_name_plural': 'Financial institutions',
                'ordering': ['name'],
            },
        ),
    ]
