# Generated by Django 6.0.5 on 2026-06-01 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('imports', '0001_initial'),
        ('institutions', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('account_type', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank account'), ('brokerage', 'Brokerage'), ('deposit', 'Deposit'), ('wallet', 'Wallet'), ('card', 'Card'), ('other', 'Other')], default='other', max_length=32)),
                ('external_id', models.CharField(blank=True, max_length=128)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('current_balance_usd', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='common.currency')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='institutions.financialinstitution')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BalanceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('balance', models.DecimalField(decimal_places=8, max_digits=20)),
                ('balance_usd', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('captured_at', models.DateTimeField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='balance_snapshots', to='accounts.account')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balance_snapshots', to='common.currency')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_snapshots', to='institutions.financialinstitution')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='balance_snapshots', to='products.product')),
            ],
            options={
                'ordering': ['-captured_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('trade', 'Trade'), ('income', 'Income'), ('transfer', 'Transfer'), ('fee', 'Fee'), ('other', 'Other')], default='other', max_length=32)),
                ('external_id', models.CharField(blank=True, max_length=128)),
                ('import_fingerprint', models.CharField(blank=True, max_length=128, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('amount_usd', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('quantity', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('unit_price', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('occurred_at', models.DateTimeField()),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.account')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='common.currency')),
                ('import_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='imports.importjob')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='products.product')),
                ('related_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_transactions', to='accounts.account')),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('institution', 'external_id'), name='unique_account_external_id_per_institution'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('account', 'external_id'), name='unique_transaction_external_id_per_account'),
        ),
    ]
