# Generated by Django 6.0.5 on 2026-08-11 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=512)),
                ('short_name', models.CharField(blank=True, max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('reg_number', models.CharField(blank=True, db_index=True, max_length=64)),
                ('swift', models.CharField(blank=True, max_length=32)),
                ('address', models.CharField(blank=True, max_length=512)),
                ('phone', models.CharField(blank=True, max_length=255)),
                ('website', models.URLField(blank=True)),
                ('nbrb_url', models.URLField(blank=True)),
                ('external_key', models.CharField(max_length=128, unique=True)),
                ('entity_type', models.CharField(choices=[('bank', 'Bank'), ('nkfo', 'Non-bank credit organization'), ('other', 'Other')], default='bank', max_length=16)),
                ('parser_code', models.CharField(blank=True, help_text='Deposit offers adapter code (empty = no rate sync).', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposit_market_banks', to='institutions.financialinstitution')),
            ],
            options={
                'verbose_name': 'Deposit bank',
                'verbose_name_plural': 'Deposit banks',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DepositOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=512)),
                ('currency', models.CharField(db_index=True, max_length=8)),
                ('rate_pct', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('rate_pct_max', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('term_text', models.CharField(blank=True, max_length=255)),
                ('term_days_min', models.PositiveIntegerField(blank=True, null=True)),
                ('term_days_max', models.PositiveIntegerField(blank=True, null=True)),
                ('min_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('is_irrevocable', models.BooleanField(blank=True, null=True)),
                ('source_url', models.URLField(blank=True)),
                ('external_id', models.CharField(max_length=255)),
                ('scraped_at', models.DateTimeField()),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='market.depositbank')),
            ],
            options={
                'verbose_name': 'Deposit offer',
                'verbose_name_plural': 'Deposit offers',
                'ordering': ['-rate_pct_max', '-rate_pct', 'bank__name', 'name'],
                'indexes': [models.Index(fields=['is_active', 'currency'], name='market_depo_is_acti_a304ea_idx'), models.Index(fields=['bank', 'is_active'], name='market_depo_bank_id_676fd4_idx')],
                'constraints': [models.UniqueConstraint(fields=('bank', 'external_id'), name='market_depositoffer_bank_external_uniq')],
            },
        ),
    ]
