# Generated by Django 6.0.5 on 2026-06-01 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rate_date', models.DateField()),
                ('rate_byn', models.DecimalField(decimal_places=6, max_digits=18)),
                ('usd_cross_rate', models.DecimalField(decimal_places=10, max_digits=18)),
                ('scale', models.PositiveIntegerField(default=1)),
                ('source', models.CharField(choices=[('nbrb', 'NBRB API')], default='nbrb', max_length=16)),
                ('source_currency_id', models.PositiveIntegerField()),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_history', to='common.currency')),
            ],
            options={
                'verbose_name': 'Exchange rate history',
                'verbose_name_plural': 'Exchange rate history',
                'ordering': ['-rate_date', 'currency__code'],
                'constraints': [models.UniqueConstraint(fields=('currency', 'rate_date', 'source'), name='unique_exchange_rate_per_day_source')],
            },
        ),
    ]
