# Generated by Cursor on 2026-06-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_exchangeratehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='code',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
