# Generated by Django 6.0.5 on 2026-06-01 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('source_type', models.CharField(choices=[('api', 'API'), ('pdf', 'PDF'), ('xls', 'XLS/XLSX'), ('manual', 'Manual')], default='manual', max_length=16)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='import_sources', to='institutions.financialinstitution')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('parsing', 'Parsing'), ('validated', 'Validated'), ('saved', 'Saved'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('file_type', models.CharField(blank=True, max_length=16)),
                ('parser_name', models.CharField(blank=True, max_length=128)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('idempotency_key', models.CharField(max_length=128)),
                ('rows_detected', models.PositiveIntegerField(default=0)),
                ('records_created', models.PositiveIntegerField(default=0)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_jobs', to='institutions.financialinstitution')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='imports.importsource')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RawImportFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('stored_path', models.CharField(max_length=512)),
                ('file_type', models.CharField(max_length=16)),
                ('mime_type', models.CharField(blank=True, max_length=128)),
                ('checksum', models.CharField(max_length=128)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_files', to='imports.importjob')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raw_files', to='imports.importsource')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='importjob',
            constraint=models.UniqueConstraint(fields=('source', 'idempotency_key'), name='unique_import_job_per_source_key'),
        ),
        migrations.AddConstraint(
            model_name='rawimportfile',
            constraint=models.UniqueConstraint(condition=models.Q(('source__isnull', False)), fields=('source', 'checksum'), name='unique_raw_import_checksum_per_source'),
        ),
    ]
